from django.urls import path
from .views import *

app_name = 'admins'

urlpatterns = [
    path('',home),
    path('dashboard/',DashboardView.as_view(),name='dashboard'),
    path('login/',LoginView.as_view(),name='login'),
    path('staff/',StaffListView.as_view(),name="staff"),
    path('staff/add/',StaffAddFormView.as_view(),name="staff-add"),
    path('staff/<int:pk>/',StaffDetailView.as_view(),name="staff-details"),
    path('staff/<int:id>/edit/',StaffEditView.as_view(),name="staff-edit"),
    # path('staff/<int:id>/get-schedule/',scheduleGetView),
    # path('staff/<int:id>/toggle-status/',StaffStatusToggle.as_view(),name="staff-toggle"),
    path('staff/<int:id>/delete/',StaffDeleteView.as_view(),name="staff-delete"),
    path('staff/<int:id>/reset-password/',StaffResetPassword.as_view(),name="staff-password-reset"),
    path('student/',StudentListView.as_view(),name="student"),
    path('student/add/',StudentAddFormView.as_view(),name="student-add-form"),
    path('student/<int:pk>/',StudentDetailView.as_view(),name="student-details"),
    path('student/<int:id>/reset-password/',StudentResetPassword.as_view(),name="student-password-reset"),
    path('student/<int:pk>/edit/',StudentUpdateFormView.as_view(),name="student-edit"),
    # path('student/<int:id>/toggle-status/',StudentStatusToggle.as_view(),name="student-toggle"),
    path('student/<int:id>/delete/',StudentDeleteView.as_view(),name="student-delete"),
    path('faculty/',FacultyListView.as_view(),name="faculty"),
    path('faculty/add/',FacultyAddView.as_view(),name="faculty-add-form"),
    path('faculty/<slug:pk>/',FacultyDetailView.as_view(),name="faculty-details"),
    path('faculty/<slug:pk>/edit/',FacultyUpdateView.as_view(),name="faculty-edit"),
    path('faculty/<slug:pk>/delete/',FacultyDeleteView.as_view(),name="faculty-delete"),
    path('department/<slug:pk>/',DepartmentDetailView.as_view(),name="department-details"),
    path('department/<slug:fid>/add/',DepartmentAddView.as_view(),name="department-add"),
    path('department/<slug:pk>/edit/',DepartmentUpdateView.as_view(),name="department-edit"),
    path('department/<slug:pk>/delete/',DepartmentDeleteView.as_view(),name="department-delete"),
    path('registration/',RegistrationListView.as_view(),name="registration"),
    path('registration/add/',RegistrationAddView.as_view(),name="registration-add-form"),
    path('registration/<int:pk>/',RegistrationDetailView.as_view(),name="registration-details"),
    path('registration/<int:id>/add-student/',RegistrationAddStudentView.as_view(),name="registration-student-add"),
    path('registration/<int:pk>/edit/',RegistrationEditView.as_view(),name="registration-edit"),
    path('registration/<int:pk>/delete/',RegistrationDeleteView.as_view(),name="registration-delete"),
    path('clearance/',ClearanceListView.as_view(),name="clearance"),
    path('clearance/add/',ClearanceAddView.as_view(),name="clearance-add-form"),
    path('clearance/<int:pk>/',ClearanceDetailView.as_view(),name="clearance-details"),
    path('clearance/<int:id>/add-student/',ClearanceAddStudentView.as_view(),name="clearance-student-add"),
    path('clearance/<int:pk>/edit/',ClearanceEditView.as_view(),name="clearance-edit"),
    path('clearance/<int:pk>/delete/',ClearanceDeleteView.as_view(),name="clearance-delete"),
    path('courses/',CourseListView.as_view(),name="courses"),
    path('courses/add/',CourseAddView.as_view(),name="course-add"),
    path('courses/<int:pk>/delete/',CourseDeleteView.as_view(),name="course-delete"),
    path('courses/<int:pk>/edit/',CourseEditView.as_view(),name="course-edit"),
    path('event/',EventView.as_view(),name="event"),
    path('event/add/',EventFormView.as_view(),name="event-add"),
    path('event/<int:id>/',EventDetailsView.as_view(),name="event-details"),
    path('event/<int:pk>/edit/',EventEditView.as_view(),name="event-edit"),
    path('event/<int:pk>/delete/',EventDeleteView.as_view(),name="event-delete"),
    path('admins-list/',AdminListView.as_view(),name="admins-list"),
    path('admins/add/',AdminCreateView.as_view(),name="admins-add"),
    path('admins/<int:pk>/',AdminDetailView.as_view(),name="admins-details"),
    path('admins/<int:id>/toggle-status/',AdminStatusToggle.as_view(),name="admins-toggle"),
    path('uploads/',UploadView.as_view(),name="uploads"),
    path('uploads/assignment/',UploadAssignmentView.as_view(),name="uploads-assignment"),
    path('uploads/assignment/<int:pk>/',UploadAssignmentDetailView.as_view(),name="uploads-assignment-details"),
    path('uploads/assignment/create/',CreateUploadAssignmentView.as_view(),name="uploads-assignment-create"),
    path('course-registration/',CourseRegistrationView.as_view(),name="course-reg"),
    path('course-registration/<int:pk>/',CourseRegistrationDetailView.as_view(),name="course-reg-details"),
    path('course-registration/<int:id>/add-course/',CourseRegistrationAddView.as_view(),name="course-reg-add"),
    path('course-registration/<int:course_id>/<int:id>/remove/',CourseRegistrationRemoveView.as_view(),name="course-reg-remove"), 
    # path('programme/class/<int:pk>/edit',ProgrammeUpdateClassView.as_view(),name="programme-edit-class"),
    # path('programme/subject/<int:pk>/edit',ProgrammeUpdateSubjectView.as_view(),name="programme-edit-subject"),
    path('settings/',SettingsView.as_view(),name="settings"),
    path('settings/password/',SettingsPasswordChangeView.as_view(),name="settings-password"),
    path('settings/session/',SessionListView.as_view(),name="school-session"),
    path('settings/session/add/',SessionCreateView.as_view(),name="school-session-add"),
    path('settings/session/<int:id>/activate/',SessionActiveView.as_view(),name="school-session-active"),
    path('logout/',LogoutView.as_view(),name="logout"),
]