# Generated by Django 3.2 on 2023-06-09 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='head_of_dept',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depthead', to='admins.staff'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='officer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
