# Generated by Django 3.2 on 2023-06-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_auto_20230609_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendies_needed',
            field=models.BooleanField(default=False),
        ),
    ]
