# Generated by Django 3.2 on 2023-06-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_event_attendies_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='loyal@gmail.com', error_messages={'unique': 'A user with that email already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
