# Generated by Django 3.2 on 2023-06-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('1', 'Head of Department'), ('2', 'Department Admin'), ('3', 'Exam Officer'), ('4', 'Normal Staff')], default='4', max_length=2),
        ),
    ]
