# Generated by Django 3.2 on 2023-06-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
