# Generated by Django 3.2 on 2023-06-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_alter_department_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.IntegerField(choices=[(1, 'First Semester'), (2, 'Second Semester')], default=1),
            preserve_default=False,
        ),
    ]
