# Generated by Django 3.2 on 2023-08-14 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0008_courseregistration_deparmentcourseline_departmentcourse_schoolsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='deparmentcourseline',
            name='dept_course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admins.departmentcourse'),
            preserve_default=False,
        ),
    ]
