# Generated by Django 3.2 on 2023-08-14 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0009_deparmentcourseline_dept_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseregistration',
            name='courses',
        ),
        migrations.CreateModel(
            name='CourseRegistrationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.course')),
                ('course_reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.courseregistration')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.schoolsession')),
            ],
        ),
    ]
