# Generated by Django 3.2 on 2023-08-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0011_auto_20230814_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsession',
            name='current',
            field=models.BooleanField(),
        ),
    ]
