# Generated by Django 3.2 on 2023-08-14 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0012_alter_schoolsession_current'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeparmentCourseLine',
            new_name='DepartmentCourseLine',
        ),
    ]
